Final

diff --git a/iot/device-rpi3b-plus/device-files/updater b/iot/device-rpi3b-plus/device-files/updater
--- a/iot/device-rpi3b-plus/device-files/updater
+++ b/iot/device-rpi3b-plus/device-files/updater
@@ -2,40 +2,146 @@
 
 KEYFILE=/run/keyfile
 BOOT_DIR=/boot/firmware/iot
-CPWD=$(pwd)
 SERIAL=$(cat /proc/cpuinfo | grep Serial | sed -n 's/^[^:]*:\(.*\)/\1/p' | xargs)
 
-STAT_SOURCE=eplayer-stats.csv
-STAT_FILE=$SERIAL-player-stats.csv
-STAT_DIR=/home/eplayer/music-player-stats
-STAT_MAX_SIZE=50
+HOME_DIR=/home/iot
+REBOOT_COUNT_FILE=$HOME_DIR/firmware-reboots.cfg
+ENC_DRIVE=$HOME_DIR/enc
 
-# Make sure stats file exist
-mkdir -p $STAT_DIR
-touch $STAT_DIR/$STAT_SOURCE
+update_log_clear() {
+	cat /dev/null > /run/update-progress.cfg
+}
 
-# Max stats size
-STAT_SIZE=$(cat /run/settings/.update | grep player-stats-max-size | sed -n 's/[^=]*=\(.*\)/\1/p')
-if [ "x$STAT_SIZE" != "x" ] && [ $STAT_SIZE -lt $STAT_MAX_SIZE ]; then
-	       STAT_MAX_SIZE=$STAT_SIZE
-fi
+update_log_publish() {	
+	echo "$(date --utc): $1" >> /run/update-progress.cfg
+	s3cmd -q -f --config /run/commission/s3cfg-upload.cfg put --no-preserve /run/update-progress.cfg s3://iot-device-upload/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-update-info.txt
+}
 
-# Truncate file to max size if too big
-STAT_CUR_SIZE=$(du -B1M $STAT_DIR/$STAT_SOURCE | cut -d$'\t' -f 1)
-if [ $STAT_CUR_SIZE -gt $STAT_MAX_SIZE ]; then
-	DELETE=$(($(cat $STAT_DIR/$STAT_SOURCE | wc -l) * ( $STAT_CUR_SIZE - $STAT_MAX_SIZE ) / $STAT_CUR_SIZE))
-	sed -i "1,$DELETE d" $STAT_DIR/$STAT_SOURCE
-fi
+upload_file() {	
+	RETRY=0
+	RETRY_MAX=10
 
-REBOOT_FILE=.reboots
-REBOOT_DIR=/home/eplayer/music-player-stats
+	while [ $RETRY -lt $RETRY_MAX ]; do
+		RETRY=$((RETRY + 1))
+		echo "Upload attempt $RETRY for $(basename $1)"
+	
+		s3cmd -q -f --config /run/commission/s3cfg-upload.cfg put --no-preserve "$1" s3://iot-device-upload/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$(basename "$1")
+		RET=$?
+
+		if [ $RET -ne 0 ]; then
+			echo "Update attempt returned (Ret: $RET)"
+		else
+			break
+		fi
+	done
+
+	if [ $RET -ne 0 ]; then
+		echo "Upload attempts for $(basename $1) failed."
+	fi
+}
+
+update_payload() {	
+
+	mkdir -p $ENC_DRIVE/update
+	mkdir -p $ENC_DRIVE/live
+
+	RETRY=0
+	RETRY_MAX=10
+
+	while [ $RETRY -lt $RETRY_MAX ]; do
+		RETRY=$((RETRY + 1))
+		echo "Sync attempt $RETRY for payload"
+	
+		s3cmd -v --config /run/commission/s3cfg-download.cfg --no-check-md5 sync --no-preserve --delete-removed s3://iot-device-download/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/payload/ $ENC_DRIVE/update/
+		RET=$?
+
+		if [ $RET -ne 0 ]; then
+			echo "Sync attempt returned (Ret: $RET)"
+		else
+			break
+		fi
+	done
+
+	if [ $RET -ne 0 ]; then
+		echo "Payload sync failed."
+	else
+		# Delete empty directories if files were removed
+		find $ENC_DRIVE/update -type d -empty -delete
+		sync
+
+		DEVICE_VER=$(cat $ENC_DRIVE/live/version.cfg)
+		LATEST_VER=$(cat $ENC_DRIVE/update/version.cfg)
+			
+		echo "Payload device version: $DEVICE_VER"
+		echo "Payload latest version: $LATEST_VER"
+	
+		if [ "x$DEVICE_VER" != "x$LATEST_VER" ]; then
+
+			echo "Updating payload (no reboot required) ..."
+
+			rsync -av --delete $ENC_DRIVE/update $ENC_DRIVE/live
+			sync
+		
+			# Delete empty directories if files were removed
+			find $ENC_DRIVE/live -type d -empty -delete
+			sync
+		fi
+
+		echo "Payload up to date."
+	fi
+}
+
+update_settings() {	
+
+	mkdir -p $BOOT_DIR/settings
+
+	RETRY=0
+	RETRY_MAX=10
+
+	while [ $RETRY -lt $RETRY_MAX ]; do
+		RETRY=$((RETRY + 1))
+		echo "Sync attempt $RETRY for settings"
+	
+		s3cmd -v --config /run/commission/s3cfg-download.cfg --no-check-md5 sync --no-preserve --delete-removed s3://iot-device-download/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/settings/ $BOOT_DIR/settings/
+		RET=$?
+
+		if [ $RET -ne 0 ]; then
+			echo "Sync attempt returned (Ret: $RET)"
+		else
+			break
+		fi
+	done
+
+	if [ $RET -ne 0 ]; then
+		echo "Settings sync failed."
+	else
+		# Delete empty directories if files were removed
+		find $ENC_DRIVE/update -type d -empty -delete
+		sync
+
+		DEVICE_VER=$(cat /run/settings/version.cfg)
+		LATEST_VER=$(cat $BOOT_DIR/settings/version.cfg)
+			
+		echo "Settings device version: $DEVICE_VER"
+		echo "Settings latest version: $LATEST_VER"
+	
+		if [ "x$DEVICE_VER" != "x$LATEST_VER" ]; then
+
+			echo "Updated settings (reboot required) ..."
+
+			sync
+			reboot
+		fi
+
+		echo "Settings up to date."
+	fi
+}
 
 # Update reboot count
-mkdir -p $REBOOT_DIR
-touch $REBOOT_DIR/$REBOOT_FILE
-echo "$(($(cat $REBOOT_DIR/$REBOOT_FILE) + 1))" > $REBOOT_DIR/$REBOOT_FILE
+touch $REBOOT_COUNT_FILE
+echo "$(($(cat $REBOOT_COUNT_FILE) + 1))" > $REBOOT_COUNT_FILE
 
-echo "Crypt-Commission: Key generation"
+# Generate key
 /bin/xkey
 
 # Make commissioning data available under /run
@@ -44,7 +150,7 @@ if [ -f $BOOT_DIR/commission.tar.gz.enc ]; then
 	cat $BOOT_DIR/commission.tar.gz.enc | openssl enc -aes-256-cbc -pbkdf2 -d -k "$(cat $KEYFILE)" | tar xz -C /run
 fi
 
-# Flash green during boot
+# Flash green during update process (cloud sync)
 /bin/led-control led0 flash 10
 
 # Wait for cloud init
@@ -93,341 +199,65 @@ else
         # Ensure time is good
 	ntpdate -v ntp.ubuntu.com
 
-	if [ -f /run/commission/.s3cfg-music ] && [ -f /run/commission/cust.cfg ] && [ -f /run/commission/site.cfg ]; then
+	if [ -f /run/commission/s3cfg-upload.cfg ] && [ -f /run/commission/s3cfg-download.cfg ] && [ -f /run/commission/cust.cfg ] && [ -f /run/commission/site.cfg ]; then
 
-		# Update Start
-		TS="$(date)"
-		L=$(/bin/offline-version)
-		O=$(/bin/online-version)
-		echo "UPDATE STARTED: $TS" > /run/.heartbeat
-		echo "UPDATE ENDED: Busy" > /run/.heartbeat
-		echo "ONLINE VERSION: $O" >> /run/.heartbeat
-		echo "LOCAL VERSION: $L" >> /run/.heartbeat
-		echo "REBOOTS: $(cat $REBOOT_DIR/$REBOOT_FILE)" >> /run/.heartbeat
-		echo "POWER: $(vcgencmd get_throttled | cut -d'=' -f2)" >> /run/.heartbeat
+		update_log_clear
 
-		s3cmd -q -f --config /run/commission/.s3cfg-ctrl put --no-preserve /run/.heartbeat s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-update.txt
+		update_log_publish "Online and ready to start update."
 		
 		# We only dump logs if enabled
-		DEBUG_LOGS=$(cat /run/settings/.update | grep debug-logs | sed -n 's/[^=]*=\(.*\)/\1/p')
+		DEBUG_LOGS=$(cat /run/settings/update.cfg | grep debug-logs | sed -n 's/[^=]*=\(.*\)/\1/p')
 	
 		if [ "x$DEBUG_LOGS" == "xyes" ]; then
 			
-			# Capture syslog / minimal logs
-			BOOT_PATH=/home/eplayer/debug/$SERIAL-boot
+			# Capture early boot logs
+			BOOT_LOGS=$SERIAL-boot
+			BOOT_PATH=/run/$BOOT_LOGS
 			mkdir -p $BOOT_PATH
 			cp -f /run/initramfs/fsck.log $BOOT_PATH/fsck.txt
 			cp -f /var/log/syslog $BOOT_PATH/syslog.txt
 			cp -f /var/log/dmesg  $BOOT_PATH/dmesg.txt
-			cd /home/eplayer/debug
-			tar -czf $SERIAL-boot.tar.gz $SERIAL-boot
-			cd $CPWD
 
-			RETRY=0
-			RETRY_MAX=10
-	
-			while [ $RETRY -lt $RETRY_MAX ]; do
-	
-				RETRY=$((RETRY + 1))
-				echo "TRY NUMBER: $RETRY"
-	
-				echo "Updating Boot Logs"
-				s3cmd -v --config /run/commission/.s3cfg-ctrl put --no-preserve $BOOT_PATH.tar.gz s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-boot.tar.gz
-				RET=$?
-		
-				if [ $RET -ne 0 ]; then
-					echo "Update attempt returned (Ret: $RET)"
-				else
-					break
-				fi
-			done	
-			
-			# Delete temporary files
-			rm -rf /home/eplayer/debug
+			tar -czf /run/$BOOT_LOGS.tar.gz -C /run/ $BOOT_LOGS
+
+			upload_file "/run/$BOOT_LOGS.tar.gz"
+
+			update_log_publish "Early boot logs published."
 	
 			# Capture logs
-			DEBUG_PATH=/home/eplayer/debug/$SERIAL-debug
+			DEBUG_LOGS=$SERIAL-debug
+			DEBUG_PATH=/run/$DEBUG_LOGS
 			mkdir -p $DEBUG_PATH
 			journalctl -k --since "7 days ago" > $DEBUG_PATH/kernel.txt
-			journalctl -u ep --since "7 days ago" > $DEBUG_PATH/ep.txt
-			journalctl -u cryptkey --since "7 days ago" > $DEBUG_PATH/cryptkey.txt
-			journalctl -u check-update --since "7 days ago" > $DEBUG_PATH/check.txt
-			journalctl -u ep-update --since "7 days ago" > $DEBUG_PATH/update.txt
-			journalctl -u hw-update --since "7 days ago" > $DEBUG_PATH/hw-test.txt
+			journalctl -u payload --since "7 days ago" > $DEBUG_PATH/payload.txt
+			journalctl -u bootstrap --since "7 days ago" > $DEBUG_PATH/bootstrap.txt
+			journalctl -u health-logger --since "7 days ago" > $DEBUG_PATH/health-logger.txt
+			journalctl -u updater --since "7 days ago" > $DEBUG_PATH/updater.txt
+			journalctl -u update-check --since "7 days ago" > $DEBUG_PATH/update-check.txt
+			journalctl -u payload-hw-check --since "7 days ago" > $DEBUG_PATH/payload-hw-check.txt
 			journalctl -u netplan-wpa-wlan0 --since "7 days ago" > $DEBUG_PATH/netplan-wifi.txt
 			journalctl -u systemd-networkd --since "7 days ago" > $DEBUG_PATH/systemd-networkd.txt
-			cp -f /etc/netplan/config.yaml $DEBUG_PATH/network-config.yaml
+			cp -f /etc/netplan/config.yaml $DEBUG_PATH/networking.cfg
 			journalctl -a --since "7 days ago" > $DEBUG_PATH/all.txt
-			cd /home/eplayer/debug
-			tar -czf $SERIAL-debug.tar.gz $SERIAL-debug
-			cd $CPWD
 
-			RETRY=0
-			RETRY_MAX=10
-	
-			while [ $RETRY -lt $RETRY_MAX ]; do
-	
-				RETRY=$((RETRY + 1))
-				echo "TRY NUMBER: $RETRY"
-	
-				echo "Updating Debug Logs"
-				s3cmd -v --config /run/commission/.s3cfg-ctrl put --no-preserve $DEBUG_PATH.tar.gz s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-debug.tar.gz
-				RET=$?
-		
-				if [ $RET -ne 0 ]; then
-					echo "Update attempt returned (Ret: $RET)"
-				else
-					break
-				fi
-			done	
-			
-			# Delete temporary files
-			rm -rf /home/eplayer/debug
+			tar -czf /run/$DEBUG_LOGS.tar.gz -C /run/ $DEBUG_LOGS
+
+			upload_file "/run/$DEBUG_LOGS.tar.gz"
+
+			update_log_publish "Debug logs published."
+
+		else
+			update_log_publish "Debug logs disabled, not uploading."
 		fi
 
-
-		RETRY=0
-		RETRY_MAX=10
-		mkdir -p /home/eplayer/enc_drive/live
-		mkdir -p /home/eplayer/enc_drive/update
-
-		while [ $RETRY -lt $RETRY_MAX ]; do
-
-			RETRY=$((RETRY + 1))
-			echo "TRY NUMBER: $RETRY"
-
-			echo "Updating Stats"
-			s3cmd -v --config /run/commission/.s3cfg-ctrl put --no-preserve $STAT_DIR/$STAT_SOURCE s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$STAT_FILE
-			RET=$?
-
-			if [ $RET -ne 0 ]; then
-				echo "Update attempt returned (Ret: $RET)"
-				continue
-			fi
-
-			echo "Updating Music"
-			s3cmd -v --config /run/commission/.s3cfg-music --no-check-md5 sync --no-preserve --delete-removed s3://ep-music/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/playlists /home/eplayer/enc_drive/update/
-			RET=$?
-			if [ $RET -ne 0 ]; then
-				echo "Update attempt returned (Ret: $RET)"
-				continue
-			fi
-
-			# Delete empty directories if files were removed
-			find /home/eplayer/enc_drive/update/playlists -type d -empty -delete
-
-			L=$(/bin/offline-version)
-			O=$(/bin/online-version)
-			
-			echo "OLD VERSION: $L"
-			echo "NEW VERSION: $O"
-	
-			if [ "x$L" != "x$O" ]; then
-
-				echo "Update -> Live"
-
-
-				# Normalizing
-				NORM_ON=$(cat /run/settings/.update | grep player-normalize-on | sed -n 's/[^=]*=\(.*\)/\1/p')
-				NORM_TARGET=$(cat /run/settings/.update | grep normalization-target | sed -n 's/[^=]*=\(.*\)/\1/p')
-				NORM_TYPE=$(cat /run/settings/.update | grep normalization-type | sed -n 's/[^=]*=\(.*\)/\1/p')
-				if [ "x$NORM_ON" == "xyes" ]; then
-				
-					L=$(/bin/offline-version)
-					O=$(/bin/online-version)
-					echo "UPDATE STARTED: $TS" > /run/.heartbeat
-					echo "UPDATE ENDED: Normalizing" > /run/.heartbeat
-					echo "ONLINE VERSION: $O" >> /run/.heartbeat
-					echo "LOCAL VERSION: $L" >> /run/.heartbeat
-					echo "REBOOTS: $(cat $REBOOT_DIR/$REBOOT_FILE)" >> /run/.heartbeat
-					echo "POWER: $(vcgencmd get_throttled | cut -d'=' -f2)" >> /run/.heartbeat
-	
-					s3cmd -q -f --config /run/commission/.s3cfg-ctrl put --no-preserve /run/.heartbeat s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-update.txt
-					OIFS="$IFS"
-					IFS=$'\n'
-	
-					# Add missing update songs in live
-					pushd /home/eplayer/enc_drive/update
-					LIVE_SONGS=($(find . -type f))
-					popd
-	
-					COUNT_MAX=${#LIVE_SONGS[@]}
-					COUNT=0
+		update_payload
 		
-					while [ $COUNT -lt $COUNT_MAX ]; do
-						IF=${LIVE_SONGS[$COUNT]}
-						OF=$(echo "${LIVE_SONGS[$COUNT]}").norm.mp4
-	
-						if [ ! -f "/home/eplayer/enc_drive/live/$OF" ]; then
-							echo "Live: new created /home/eplayer/enc_drive/live/$IF"
-							mkdir -p "$(dirname "/home/eplayer/enc_drive/live/$IF")"
-							cp -f "/home/eplayer/enc_drive/update/$IF" "/home/eplayer/enc_drive/live/$IF"
-						fi
-	
-						COUNT=$((COUNT + 1))
-					done
-					
-					# Remove old songs from live
-					pushd /home/eplayer/enc_drive/live
-					LIVE_SONGS=($(find . -type f | grep '.norm.mp4' | sed 's/.norm.mp4//g'))
-					popd
-	
-					COUNT_MAX=${#LIVE_SONGS[@]}
-					COUNT=0
+		update_log_publish "Payload update processed."
+
+		update_settings
 		
-					while [ $COUNT -lt $COUNT_MAX ]; do
-						IF=${LIVE_SONGS[$COUNT]}
-						OF=${LIVE_SONGS[$COUNT]}.norm.mp4
-	
-						if [ ! -f "/home/eplayer/enc_drive/update/$IF" ]; then
-							echo "Live: deleted /home/eplayer/enc_drive/live/$OF"
-							rm -f "/home/eplayer/enc_drive/live/$OF"
-						fi
-	
-						COUNT=$((COUNT + 1))
-					done
-	
-	
-					# Delete empty directories if files were removed
-					find /home/eplayer/enc_drive/live/playlists -type d -empty -delete
+		update_log_publish "Payload update processed."
 
-
-					echo "Normalizing"
-
-					if [ "x$NORM_TYPE" != "xebu" ] && [ "x$NORM_TYPE" != "xrms" ] && [ "x$NORM_TYPE" != "xpeak" ]; then
-						echo "Fixing invalid norm type...($NORM_TYPE -> ebu)"
-						NORM_TYPE=ebu
-					fi
-					
-					echo "Normalize type: $NORM_TYPE "
-
-					if [ "x$NORM_TYPE" == "xebu" ]; then
-						TARGET_MAX=-5.0
-					else
-						TARGET_MAX=0.0
-					fi
-					
-					if [ "x$NORM_TARGET" == "x" ] || [ $(echo "$NORM_TARGET < -25" | bc) -eq 1 ] || [ $(echo "$NORM_TARGET > $TARGET_MAX" | bc) -eq 1 ]; then
-						echo "Fixing invalid norm target...($NORM_TARGET -> -10)"
-						NORM_TARGET=-10
-					fi
-					
-					echo "Normalize target: $NORM_TARGET dB"
-					
-					T="/tmp/encpids"
-					rm -rf $T
-					mkdir -p $T
-	
-					ALL=($(find /home/eplayer/enc_drive/live -type f | grep -v '.norm.mp4'))
-					COUNT_MAX=${#ALL[@]}
-					COUNT=0
-		
-					NORM_START=$(date +"%s")
-	
-					while [ $COUNT -lt $COUNT_MAX ]; do
-						IF=${ALL[$COUNT]}
-						OF=${ALL[$COUNT]}.norm.mp4
-	
-						bash -c "touch $T/\$\$; ffmpeg-normalize \"$IF\" -o \"$OF\" -c:a aac -b:a 192k -ar 48000 -nt $NORM_TYPE -t $NORM_TARGET -tp 0.0 -p -v -f; rm -f \"$IF\"; rm -f $T/\$\$" &
-
-						# Print busy count
-						echo "Normalizations in progress: $(ls $T | wc -l)"
-	
-						# Wait until less than 4 encoding sessions are running
-						while [ true ]; do
-							ENC_RUN=$(ls $T | wc -l)
-							if [ $ENC_RUN -lt 4 ]; then
-								break
-							fi
-	
-							sleep 1
-						done
-		
-						COUNT=$((COUNT + 1))
-					done
-
-					# Wait until last ones are complete
-					while [ true ]; do
-						ENC_RUN=$(ls $T | wc -l)
-						if [ $ENC_RUN -eq 0 ]; then
-							break
-						fi
-					
-						sleep 1
-					done
-	
-					NORM_END=$(date +"%s")
-					NORM_TIME=$(date +%T --date="1970-01-01 + $((NORM_END - NORM_START)) seconds")
-					sync
-	
-					echo "Normalizing Complete: $COUNT_MAX tracks, in $NORM_TIME"
-		
-					IFS="$OIFS"
-					rm -rf $T
-				else
-					echo "Player Normalizing disabled in settings"
-					echo "Copying pre-normalized files only"
-					
-					mkdir -p /home/eplayer/enc_drive/live
-					rsync -av --delete /home/eplayer/enc_drive/update/ /home/eplayer/enc_drive/live/
-
-					# Delete empty directories if files were removed
-					find /home/eplayer/enc_drive/live/playlists -type d -empty -delete
-					sync
-
-					echo "Copying pre-normalized files done"
-				fi
-	
-				OLD_VERSION=$(cat /boot/firmware/eplayer/settings/version.cfg)
-		
-				echo "Update Settings"
-				s3cmd -v --config /run/commission/.s3cfg-music sync --no-preserve s3://ep-settings/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/settings/ /boot/firmware/eplayer/settings/
-				RET=$?
-				if [ $RET -ne 0 ]; then
-					echo "Update attempt returned (Ret: $RET)"
-					continue
-				fi
-		
-				NEW_VERSION=$(cat /boot/firmware/eplayer/settings/version.cfg)
-
-				echo "OLD VERSION: $OLD_VERSION"
-				echo "NEW VERSION: $NEW_VERSION"
-				echo "Update Compelted (including normalization) - Rebooting" 
-		
-				# Update End
-				TE="$(date)"
-				L=$(/bin/offline-version)
-				O=$(/bin/online-version)
-				echo "UPDATE STARTED: $TS" > /run/.heartbeat
-				echo "UPDATE ENDED: $TE" >> /run/.heartbeat
-				echo "ONLINE VERSION: $O" >> /run/.heartbeat
-				echo "LOCAL VERSION: $L" >> /run/.heartbeat
-				echo "REBOOTS: $(cat $REBOOT_DIR/$REBOOT_FILE)" >> /run/.heartbeat
-				echo "POWER: $(vcgencmd get_throttled | cut -d'=' -f2)" >> /run/.heartbeat
-				echo "INFO: Update Success" >> /run/.heartbeat
-				s3cmd -q -f --config /run/commission/.s3cfg-ctrl put --no-preserve /run/.heartbeat s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-update.txt
-		
-				# Reboot to apply updates
-				reboot
-			else
-				# Update End
-				TE="$(date)"
-				L=$(/bin/offline-version)
-				O=$(/bin/online-version)
-				echo "UPDATE STARTED: $TS" > /run/.heartbeat
-				echo "UPDATE ENDED: $TE" >> /run/.heartbeat
-				echo "ONLINE VERSION: $O" >> /run/.heartbeat
-				echo "LOCAL VERSION: $L" >> /run/.heartbeat
-				echo "REBOOTS: $(cat $REBOOT_DIR/$REBOOT_FILE)" >> /run/.heartbeat
-				echo "POWER: $(vcgencmd get_throttled | cut -d'=' -f2)" >> /run/.heartbeat
-				echo "INFO: No Update" >> /run/.heartbeat
-				s3cmd -q -f --config /run/commission/.s3cfg-ctrl put --no-preserve /run/.heartbeat s3://ep-stats/$(cat /run/commission/cust.cfg)/$(cat /run/commission/site.cfg)/$SERIAL-update.txt
-				
-				# No update continue to boot
-				break
-			fi
-
-		done
 	else
 		echo "Commissioning and Settings files not found for required S3 update"
 	fi	
